### ISSUE TITLE
拉黑剩余时间计算/显示错误

### ISSUE THREAD

**Issue by GOUKI9999** [tty228/luci-app-wechatpush#230]
将默认拉黑时间1天改为7天   （604800秒）后
可以看到新加入的ip 显示  在最后一行，格式如下

222.213.236.234 expires 18h16m53s670ms 
145.239.83.33 timeout 604800

但一段时间后重新查看时

139.144.181.138 expires 20h40m59s930ms
145.239.83.33 expires 22h50m26s860ms

似乎又按默认的一天进行了倒计时，目前无法判断是哪个步骤错误，是实际的倒计时错误还是显示错误

**Comment by tty228** [comment]
应该是修改设置后，防火墙规则没有重置，nft 添加 ip 好像是只能使用 ip 集合中的默认时间

**Comment by GOUKI9999** [comment]
收到，那这里时间修改的时候点击应用之后，应该执行重置nft，使得规则重新设置的时间生效吗？原有的ip集合时间会变成怎样呢

**Comment by tty228** [comment]
> 收到，那这里时间修改的时候点击应用之后，应该执行重置nft，使得规则重新设置的时间生效吗？原有的ip集合时间会变成怎样呢

重置的话，原有的 IP 集合会被清空，然后从文本里再次添加，时间会被重置
而且这个不是好办法，应该有修改 IP 集合超时时间的命令吧
开始的时候没查到，后来就忘了这事
我再找找

`( opkg list-installed|grep -w -q ^firewall4 ) && nft add element inet fw4 $ipset_name { $1 } && return #没找到刷新时间的命令，删除再添加
	ipset -exist add $ipset_name $1 timeout $login_ip_white_timeout`

**Comment by tty228** [comment]
复制一下源码，然后
`/etc/init.d/wechatpush reload`  #重启服务

**Comment by GOUKI9999** [comment]
……你说的是

**Comment by tty228** [comment]
> ……您说的是 /etc/init.d/serverchan reload 吧

→_→，没更新到 3.0 的话，就是` /etc/init.d/serverchan reload`
这个令人迷惑的插件名，我前几天悄咪咪改掉了
