### ISSUE TITLE
api错误

### ISSUE THREAD

**Issue by SakuraFallingMad** [tty228/luci-app-wechatpush#231]
2023-06-04 10:39:48 【！！！】json 文件格式错误，这不是一个标准的 json 文件，请检查 /usr/share/wechatpush/api/wechatpush.json 文件是否有特殊符号未转义或语法错误

好像实际文件不存在

**Comment by tty228** [comment]
> wechatpush

应该是 /usr/share/wechatpush/api/serverchan.json 批量替换的时候弄错了

**Comment by tty228** [comment]
参考 https://github.com/tty228/luci-app-wechatpush/commit/739ed9f64d088e53c5e2f3e14bd38da95ace9422 修改一下 /www/luci-static/resources/view/wechatpush/config.js 文件，然后刷新一下页面，重新报错设置

**Comment by SakuraFallingMad** [comment]
ok，还有个发现个小瑕疵，汉化文件有问题，用的immortalwrt 21.02分支，luci无中文
![图片](https://github.com/tty228/luci-app-wechatpush/assets/31793080/6eb51779-8a16-47d2-8ab0-a7a64f6ec1a6)

**Comment by tty228** [comment]
不应该啊，隐私模式看一下

**Comment by tty228** [comment]
清一下缓存，或者 Ctrl + Shift + R 强制刷新应该就好了

**Comment by SakuraFallingMad** [comment]
清了缓存 原来还要退进程再进去就正常了。。
