### ISSUE TITLE
2.06.2仍然有重复推送的问题

### ISSUE THREAD

**Issue by GOUKI9999** [tty228/luci-app-wechatpush#232]
手头的一个旧k3只能用旧版luci的，问题和之前反馈的估计相同 #226

**Comment by tty228** [comment]
旧版 LuCI 不是没有登陆日志的吗

**Comment by GOUKI9999** [comment]
> 旧版 LuCI 不是没有登陆日志的吗

啊但是确实有，情况和之前相同现象，同一个ip每分钟发一次，但实际上应该已经被加iptables了吧（未确认）

之前用的是07.1发现这一问题后本想升级但高版本无法用，以后
force downgrade到06.2的不知道和这个有没有关系

**Comment by tty228** [comment]
重新拉一下源码吧，刚改过了
可能是没有 Web 的登陆，但 SSH 的正常吧，详见
https://github.com/tty228/luci-app-wechatpush/issues/190

**Comment by GOUKI9999** [comment]
![image](https://github.com/tty228/luci-app-wechatpush/assets/11640942/f273492d-68f2-403f-be43-d17489532665)
多谢，不过目前没有编译环境，只能等老板更一个旧版luci的最终版了

**Comment by tty228** [comment]
> ![image](https://user-images.githubusercontent.com/11640942/243240175-f273492d-68f2-403f-be43-d17489532665.png) 多谢，不过目前没有编译环境，只能等老板更一个旧版luci的最终版了，图为日志，看起来像是之前的屏蔽但未清除记录的表现

手动修改一下，然后重启启动也是一样的

**Comment by GOUKI9999** [comment]
好的老板，另外早上想到刚才忘了说，这个屏蔽如果好用……我就不用什么beardropper了，所以这部分功能，是否可以考虑做成只包含拉黑但不推送，或者定时推送一次屏蔽结果呢？（因为现在是屏蔽就默认推送一次？）

一来是扫端口客观存在，二来这个情况频繁但只要及时fail to ban，重要程度不高，所以如果可行，是否可以指定通知间隔，每次只通知间隔中是否增加了和增加了哪些ip这样？
例如：1h/8h/24h一次？

**Comment by GOUKI9999** [comment]
![image](https://github.com/tty228/luci-app-wechatpush/assets/11640942/23eae872-a44f-40d4-b3ae-7b9e7f8c389d)
但……我不知道改哪里啊大佬，等我pull下来看看的

**Comment by tty228** [comment]
> ![image](https://user-images.githubusercontent.com/11640942/243241174-23eae872-a44f-40d4-b3ae-7b9e7f8c389d.png) 但……我不知道改哪里啊大佬，等我pull下来看看的 ![image](https://user-images.githubusercontent.com/11640942/243241586-332532bb-2345-47c2-bb97-ca08c6241d75.png) 这几处对么

对

你说的那两处功能 2.08 和 3.01 有加入，具体的 Commit 在这里
https://github.com/tty228/luci-app-wechatpush/commit/c718bac482ef67034a7564294308a9875d0f8d18
https://github.com/tty228/luci-app-wechatpush/commit/73fdd17bb4511af04652ef88b1057f1a4935e7f9

不过其实还有两个修复用的提交
https://github.com/tty228/luci-app-wechatpush/commit/d04c70632e251050b65ec6b20c040ff3e6fa5cf9
https://github.com/tty228/luci-app-wechatpush/commit/c00b00ace90071c7088efbb629d60eff8c383e21

大雕那边的源码，LuCI 是没有登陆提示的，所以不太想改了，改了也基本用不到

而且实在是不想维护两个版本了，因为 js 对前端设置页面做了一些美化，配置文件的变量名有变化，不能单纯的复制源码

**Comment by tty228** [comment]
至于实用性的话，主要还是封禁速度不够理想，因为没有做单独的模块
实际封禁速度会延后 检测时间间隔（秒）+检测在线设备所需时间
可以通过增大 最大并发进程数 或直接关闭主动检测来减少这个时间，但还是存在这个问题
因为一开始做插件的时候没想过做这么多功能，所以妄想单文件尽量不生成临时文件（计划破灭），但导致现在新加的功能很尴尬，实在不想动大手术了
只能说框架没做好了

**Comment by GOUKI9999** [comment]
2023-06-06 12:53:22 【！！！】设备 123.113.105.87 (中国  北京) 通过 SSH 频繁尝试登录
最新3.1.0  已经选择登录提醒免打扰--仅记录到日志

仍然接送到日志中如上推送，是我理解有误还是不该同时勾选“免刷屏”

再次感谢您的开发工作

**Comment by tty228** [comment]
事实上频繁登录不会检测上一条日志是否存在，因为拉黑之后应该不会再有流量，所以不会再有信息产生才对
这个 IP 的信息刷了多少条

**Comment by GOUKI9999** [comment]
![image](https://github.com/tty228/luci-app-wechatpush/assets/11640942/ea19927a-764b-49e3-b899-576c086ad061)
这是调整设置后保存重启服务之后的部分，可以看到这个ip产生了**一共两条**，而且相距超过了3分钟，很奇怪
另外我理解没错的话，选择了记录到日志后，不是这些频繁登录信息都不应该再被推送吗？
为何还是推送了呢。

**Comment by tty228** [comment]
看了一下，是我记错了，这个功能是 登录提醒日志免刷屏，只针对登录提醒 :anguished:
改天再改了
IP 重复推送那个没明白什么原因
负载报警那个的话，因为低性能的设备很容易峰值超过负载，但其实没有推送信息的必要，所以当时是设置的连续五分钟超过预设值才会推送

**Comment by GOUKI9999** [comment]
> 看了一下，是我记错了，这个功能是 登录提醒日志免刷屏，只针对登录提醒 😧 改天再改了 IP 重复推送那个没明白什么原因
哦，这里那就是我理解错误，因为排版上看，登录提醒是父功能，包含web/ssh的登录和fail2ban
我以为错误登录的功能也是“登录提醒”的一部分，因此看到新加的免打扰以为无论是普通登录还是错误登录都会根据设定免提醒

>负载报警那个的话，因为低性能的设备很容易峰值超过负载，但其实没有推送信的必要，所以当时是设置的连续五分钟超过预设值才会推送
这里是我忘掉了连续5分钟这个设置，是我误解读日志了不好意思

**Comment by tty228** [comment]
> 我以为错误登录的功能也是“登录提醒”的一部分，因此看到新加的免打扰以为无论是普通登录还是错误登录都会根据设定免提醒
> 
> >

因为我这没开公网端口，异常登陆事件其实很少，所以就没想起来把异常登陆事件整进去，纯粹是失误

**Comment by tty228** [comment]
如果扫描的次数这么多的话，问题应该出在

`# 读取信息后清空，避免重复统计次数`
`echo "" > ${dir}login_monitor`

到检测并拉黑这一段代码过程中，重新产生了日志输出
因为系统日志检测通过 `logread -f -p notice` 命令来检测新增的行
所以这个 bug 应该存在于整个登录提醒的模块，只是别的功能不会有这么频繁的日志输出，体现不出来而已
我看看是优化一下流程还是推送和输出日志前检测
鸽一下，明天上班摸鱼再改，反正不影响使用 :smirk:

**Comment by tty228** [comment]
Wed Jun 7 18:13:51 2023 authpriv.info dropbear[15074]: Exit before auth from <220.174.25.172:37693>: Timeout before auth
这一行命令 [15074] 对应的是
Wed Jun 7 18:08:51 2023 authpriv.info dropbear[15074]: Child connection from 220.174.25.172:37693
这个 IP 在 18:08:51 已经拉黑成功了，18:13:51 的时候超时退出，拉黑功能应该是没有问题的

**Comment by tty228** [comment]
> 好的老板既然可以摸鱼，不如顺手编一个2.06系列最终版吧

bug 是修不完的，不可能有最终版 :anguished:
不加新功能也会遇到 API 失效 :disappointed_relieved:

**Comment by GOUKI9999** [comment]
> Wed Jun 7 18:13:51 2023 authpriv.info dropbear[15074]: Exit before auth from <220.174.25.172:37693>: Timeout before auth 这一行日志 [15074] 对应的是 Wed Jun 7 18:08:51 2023 authpriv.info dropbear[15074]: Child connection from 220.174.25.172:37693 这个 IP 在 18:08:51 已经拉黑成功了，18:13:51 的时候超时退出，拉黑功能应该是没有问题的

是的，所以只有拉黑到再次处理log的过程中，重复处理日志的问题，应该不存在拉黑是否生效的问题。

**Comment by tty228** [comment]
现在登陆提醒为实时响应，流程为 实时检测→拉黑→记录拉黑的 IP →推送循环中检测拉黑的 IP 并生成推送信息

其实应该还是有微小可能推送两次 IP，不过实在是觉得每次添加黑名单前都检测一遍黑名单太多余了，先这样吧

**Comment by GOUKI9999** [comment]
升级到3.2.0，安装后第一次启动出现日志
2023-06-09 11:52:02 【！！！】设备 1.22.229.83 (印度  印度) 通过 SSH 频繁尝试登录
2023-06-09 11:52:02 【！！！】设备 103.140.126.146 (亚太地区  亚太地区) 通过 SSH 频繁尝试登录
——
中略，约180条
——
2023-06-09 11:53:08 【！！！】设备 95.252.157.18 (意大利 ) 通过 SSH 频繁尝试登录
2023-06-09 11:53:09 【！！！】设备 96.91.198.250 (美国 ) 通过 SSH 频繁尝试登录
2023-06-09 11:54:09  【清理】日志超出上限，删除前 100 条
2023-06-09 11:54:46  【清理】日志超出上限，删除前 100 条

以为是要重新整理之前的黑名单并加入当前黑名单，但两个问题：
1，黑名单仍然为空（也没太大问题），尚未观察到新的封禁频繁登录的功能是否正常工作
2，因为条数较多，直接就被清理了

另一个问题：
点击发送测试按钮，反馈为“发送失败”（按钮下方灰字）
实际发送成功
2023-06-09 11:59:01 【debug】json 文件已保存至：/tmp/wechatpush/debug_send_json
2023-06-09 11:59:01 【debug】推送内容预览文件保存至：/tmp/wechatpush/debug_send_content
2023-06-09 11:59:01 【debug】如果收不到信息，请检查 /tmp/wechatpush/debug_send_data 文件，或使用下列命令手动测试返回值 (可能需要关闭日志自动刷新方便选中)
2023-06-09 11:59:01 【debug】curl -X POST -H "Content-Type: application/json" -d "@/tmp/wechatpush/debug_send_data" "https://api.telegram.org/bot5516687521:AAEM1Q0vc730-Pwc95pfB8HUqCJ5w3wLxyw/sendMessage"  
2023-06-09 11:59:02 【telegram】定时推送任务完成

tg已经正常收到

**Comment by tty228** [comment]
问题 1 应该是我偷懒所引起的，之前的版本 ${dir}web_login、${dir}ssh_login 等文件是用来记录 IP 登陆记录的
3.2 直接还是用了这个文件，用来记录已经被拉黑，需要推送的 IP
不过后续就不会这样了
（但是这次会引起误封，因为只登陆了一次的设备也会被封禁
（你 IP 记录可真多 :anguished: ，我开了一天端口没人扫我

问题 2 是语法错误导致

修了

**Comment by GOUKI9999** [comment]
其实有zerotier之类的打洞，我也觉得端口暴露公网其实不安全，但是考虑到特殊情况，路由器22映射了一个高端口，web也映射了一个，可能还是北京联通的ip段容易被扫吧，我就当小白鼠了。这还是因为之前推送频繁，把5次的阈值设置到20才一天只有十几到几十个，否则会多好几倍。
另外web我看syslog也有日志，那倒是web安全很多没人扫了，这样岂不是应该用web映射到外网做入口，需要ssh用的时候临时web开方便安全？（实际上想了一下还是觉得麻烦）
大佬更新勤奋，佩服。

**Comment by tty228** [comment]
有端口敲门啊

**Comment by GOUKI9999** [comment]
> 有端口敲门啊

???……！
我看说明，分明就是“我写不完不写了”，十分理解。
于是根本就没打开

**Comment by tty228** [comment]
Web 或 SSH 登录成功，也就是在原先推送和记录日志的基础上，对此 IP 开放端口或开放指定的端口转发
