### ISSUE TITLE
定时任务不会自动推送，手动推送可以收到消息

### ISSUE THREAD

**Issue by ardenyang** [tty228/luci-app-wechatpush#233]
安装的wechatpush版本是：luci-app-wechatpush | git-24.160.45303-cf6dd15
Openwrt的版本是：分支: 23.05.0-rc1，内核: 5.15.114。Op镜像下载地址：https://supes.top/

问题现象：定时推送设置的是计划任务间隔4小时发送，然后保存并应用。但定时任务不会自动推送，手动推送可以收到消息。

问题排查：查看Openwrt的系统-计划任务（/cgi-bin/luci/admin/system/crontab），发现并没有wechatpush的任务；
手动增加：0 */4 * * * /usr/share/wechatpush/wechatpush send &
然后就能自动收到定时推送的消息了。感觉问题是在定时推送设置保存的时候，程序没有在corntab里面增加推送任务导致的问题。
麻烦检查一下，多谢。

**Comment by tty228** [comment]
网页端那边变量名漏掉了

**Comment by ardenyang** [comment]
多谢修复
