### ISSUE TITLE
新版本插件无效

### ISSUE THREAD

**Issue by MrVicent** [tty228/luci-app-wechatpush#234]
用lean的编译（https://github.com/coolsnowwolf/lede）
最新版编译后找不到wechatpush
请问是什么原因 或者 有什么方法解决

**Comment by MrVicent** [comment]
![image](https://github.com/tty228/luci-app-wechatpush/assets/50162258/661faf89-9e5e-4cc0-8f43-33e795211c88)

**Comment by tty228** [comment]
v2.06.2 之后的版本不再支持 LuCI 18.06，如需编译，请使用 openwrt-18.06 分支，拉取源码时请使用 git clone -b openwrt-18.06 https://github.com/tty228/luci-app-wechatpush.git 命令
