### ISSUE TITLE
PVE虚拟机获取到的温度不是cpu温度，而是固态的温度

### ISSUE THREAD

**Issue by m0eak** [tty228/luci-app-wechatpush#236]
![image](https://github.com/tty228/luci-app-wechatpush/assets/50049180/32a2dc49-6e41-46ca-b41f-0ba2ea793b5d)
![image](https://github.com/tty228/luci-app-wechatpush/assets/50049180/422eb33b-e320-4828-8a16-097a3cfea685)
版本是 2.01.4-9

**Comment by tty228** [comment]
升级版本或使用自定义命令
