### ISSUE TITLE
【建议】能否加入自定义判断条件/wxpusher推送的参数填写

### ISSUE THREAD

**Issue by GOUKI9999** [tty228/luci-app-wechatpush#240]
![image](https://github.com/tty228/luci-app-wechatpush/assets/11640942/248bf81b-5313-4168-87fd-c70e71c761da)
这是我一个软路由的实际load情况，我也没查到是什么计划运行的程序或其他进程导致有规律地出现负载暂时上升（可能是uu加速器或openclash之类比较重的）

这个情况会导致目前默认的“负载报警”相当频繁地报警——但实际上我的情况就是正好大约每一个小时多一点会有个五六分钟的高负载时段，大概也还算正常且目前看不碍事。

因为这个负载峰值较高，所以通过调整阈值是不太现实的，所以想的是如果能把cpu报警的load检测改为连续10分钟超过阈值就好了，但目前是不能自定义

如果这里支持自定义阈值检查持续时间和间隔时间可能会有助于消减误报情况，虽然我这里是个例，但理论上如果其他人也有定期运行的crontab或周期性程序，也可以通过这方法避免产生误报。

因为不懂luci，没有能力提提pull request，就写这里了，见谅

**Comment by tty228** [comment]
还在出差，下个月再说吧

**Comment by tty228** [comment]
应该是可以了，设置弄到免打扰选项卡去了，设置项有点多，感觉好乱 :frowning:

**Comment by GOUKI9999** [comment]
CPU 负载过高
    CPU 负载已连续五分钟超过预设
    接下来一小 时不再提示
    当前负载：4.90
    
    今天qa了一下，感觉提示的文字信息部分是否应该也改成变量匹配自定义的“超过阈值持续时间”和“免打扰时间”
以这条提示为例，实际上我已经将默认的300秒和3600改为了600和7200，但文字应该仍然是写死的原定值
另及CPU报警的配置信息处的原信息
“设备报警只会在连续五分钟超过设定值时才会推送，一个小时内不会再提醒第二次。”
似也可改为“设备报警连续持续到预设时间后才会推送，并且不会连续提醒，持续和间隔时间请在免打扰tab内设置”

**Comment by tty228** [comment]
完全忘了还有文字

**Comment by GOUKI9999** [comment]
另发现了一个小问题，先提这个下面不另开issue了吧
在使用wxpusher的推送时昨天测试了一下发现必须填写apptoken（必须）
同时uids和topicids都不能为空否则会提示错误，但我查看了一下他们的api说明：

  "topicIds":[ //发送目标的topicId，是一个数组！！！，也就是群发，使用uids单发的时候， 可以不传。
      123
  ],
  "uids":[//发送目标的UID，是一个数组。注意uids和topicIds可以同时填写，也可以只填写一个。
      "UID_xxxx"

理解没错的话这两个参数**其中一个不为空**即可，我测试了一下同时填写了自己的uid和自己所在的topic，会收到重复的两条

我之前一段时间没用wxpusher，稍微有点困惑因为之前是只给自己发，肯定没有填topicid，甚至就没建立topic，测试的topic都是昨天建立的，现在这里变成必填的话单发也就是只用uid甚至无法执行了？不记得之前是这样还是中间修改过了。
