### ISSUE TITLE
新安装的 OpenWrt ，定时任务列表为空时，无法添加定时任务

### ISSUE THREAD

**Issue by tty228** [tty228/luci-app-wechatpush#241]
https://github.com/tty228/luci-app-wechatpush/blob/master/root/usr/share/wechatpush/wechatpush#L651

`crontab -l` 返回值为错误，导致代码未执行
待修复

**Comment by qin9125** [comment]
手动自己加定时任务吧，跟我一样，定时任务插件自动增加不了
