### ISSUE TITLE
安装最新版后界面部分为英文

### ISSUE THREAD

**Issue by liuwleo** [tty228/luci-app-wechatpush#242]
X-86 64的openwrt，安装主程序和语言包后界面翻译不全。
![image](https://github.com/tty228/luci-app-wechatpush/assets/49121177/9d5aa9ed-0fec-4086-9e21-ea2be4f85283)

**Comment by tty228** [comment]
先卸载语言包再重新安装，应该是你 OpenWrt 编译的版本号比我的大，安装语言包失败

**Comment by liuwleo** [comment]
> 先卸载语言包再重新安装，应该是你 OpenWrt 编译的版本号比我的大，安装语言包失败

明白，我重新试一下，多谢。

**Comment by youzi488** [comment]
> 先卸载语言包再重新安装，应该是你 OpenWrt 编译的版本号比我的大，安装语言包失败

重新安装后还是部分界面为英文
