### ISSUE TITLE
自定义推送格式到底怎么用？

### ISSUE THREAD

**Issue by lozn00** [tty228/luci-app-wechatpush#244]
我需要发起一个get推送
比如 http://192.168.3.3:10?read={msgcontent}
这种应该怎么改呀？
```


{
	"_//": "-------------------------------------------------------------------------------",
    "_readme": "这是 自定义 api 文件，这里以 telegram 为例",
    "_readme": "特殊符号请使用斜杠转义，变量使用 ${var} 表示",
    "_//": "-------------------------------------------------------------------------------",
    "_api": "【DIY 推送】",
    "_url": "api 地址",
    "_data": "生成的 json 文件路径，一般不需要改，如 api 不支持 json，请参考 serverchan 推送接口",
    "_content_type": "post 内容类型，这里为 json",
    "_//": "-------------------------------------------------------------------------------",
    "_str_title_start": "标题粗体字开始符号",
    "_str_title_end": "标题粗体字结束符号",
    "_str_linefeed": "换行符号",
    "_str_splitline": "换行+分隔符",
    "_str_space": "空格",
    "_str_tab": "TAB（用在行首，生成文字区块）",
    "_//": "-------------------------------------------------------------------------------",
    "_type":
      {
		"_readme": "type 对象因为需要转义变量，前后必须使用 斜杠+双引号 转义",
		"_readme": "参照上文说明，填写下文相关参数"
      },
    "_//": "-------------------------------------------------------------------------------",
    
    "url": " http://192.168.3.3:10?read=${str_title_start}${1}${str_title_end}${str_splitline}${nowtime}${2}",
    "data": "@${tempjsonpath}",
    "content_type": "Content-Type: application/json",
    "str_title_start": "<b>",
    "str_title_end": "</b>",
    "str_linefeed": "\\n",
    "str_splitline": "\\n----\\n",
    "str_space": " ",
    "str_tab": "    ",
    "type":
      {
		"text":"\"${str_title_start}${1}${str_title_end}${str_splitline}${nowtime}${2}\"",
		"chat_id":"\"${chat_id}\"",
        "parse_mode":"\"HTML\""
      }
}
```

**Comment by QwindF** [comment]
同问，url请求方式为get怎么传递消息

**Comment by tty228** [comment]
get 推送参考 /usr/share/wechatpush/api/serverchan.json
```
{
    "_api": "这是 serverchan api 文件",
    "_api": "【serverchan】",

    "url": "\"https://sctapi.ftqq.com/${sckey}.send\"",
    "data": "\"text=${1}&desp=${nowtime}${str_linefeed}${2}\"",
    "content_type": "Content-Type:application/x-www-form-urlencoded",
    "str_title_start": "#### ",
    "str_title_end": "",
    "str_linefeed": "%0D%0A%0D%0A",
    "str_splitline": "%0D%0A%0D%0A----%0D%0A%0D%0A",
    "str_space": " ",
    "str_tab": "    ",
    "type":
      {
      }
}
```

**Comment by chengpei** [comment]
调通了吗？我也不知道怎么自定义。。

**Comment by tty228** [comment]
GET：修改 ``` "url": "\"https://sctapi.ftqq.com/${sckey}.send\"", ```，使用你的 URL 地址替换掉 `https://sctapi.ftqq.com/${sckey}.send` 这一段即可
无特殊推送内容要求，data 字段不需要修改
内容格式自行修改：
"str_title_start": 粗体字段开始代码
"str_title_end": 粗体字段结束代码
"str_linefeed": 换行符
"str_splitline": 分隔符（前后自带换行）
"str_space": 空格
"str_tab": tab 符号

**Comment by HalcyonDaysssss** [comment]
bark自定义推送如下：
{
    "_api": "【Bark推送】",
    "url": "https://api.day.app/你自己的token/",
    "data": "@${tempjsonpath}",
    "content_type": "Content-Type: application/json; charset=utf-8",
    "str_title_start": "【",
    "str_title_end": "】",
    "str_linefeed": "\\n",
    "str_splitline": "\\n\\n",
    "str_space": " ",
    "str_tab": " ",
    "type": {
        "device_key": "\"你自己的token\"",
        "title": "\"${1}\"",
        "body": "\"${nowtime}${2}\"",
        "ext_params": {
            "group": "\"iStoreOS\"",
            "isArchive": "1",
            "icon": "\"http://day.app/assets/images/avatar.jpg\"",
            "level": "\"active\""
        }
    }
}

**Comment by CK-Tex** [comment]
我补充一个Zulip能用的：

``` json
{
  "_api": "【Zulip】",
  "url": "\"http://<Bot邮箱地址>:<Bot API Key>@<访问FQDN或IP>/api/v1/messages\"",
  "data": "\"type=private&to=<接收者邮箱地址>&content=${str_title_start}${1}${str_title_end}${str_splitline}${nowtime}${2}\"",
  "content_type": "Content-Type:application/x-www-form-urlencoded",
  "str_title_start": "**",
  "str_title_end": "**",
  "str_linefeed": "\n\n",
  "str_splitline": "\n\n----\n\n",
  "str_space": " ",
  "str_tab": "    ",
  "type": {}
}
```

^1 Bot邮箱地址中间的 `@` 转译成 `%40` 。

**Comment by jw10126121** [comment]
有没有钉钉能用的配置文件呀

**Comment by zcluo** [comment]
来个gotify的。可以自己的VPS上搭建一个SERVER
{
    "_api": "【gotify推送】",
    "url": "https://domain:port/message?token={token}",
    "data": "@${tempjsonpath}",
    "content_type": "Content-Type: application/json",
    "str_title_start": "【",
    "str_title_end": "】",
    "str_linefeed": "\\n",
    "str_splitline": "\\n\\n",
    "str_space": " ",
    "str_tab": " ",
    "type": {
        "priority": "0",
        "title": "\"${1}\"",
        "message": "\"${str_title_start}${1}${str_title_end}${str_splitline}${nowtime}${2}\""
        
    }
}

**Comment by jw10126121** [comment]
> 来个gotify的。可以自己的VPS上搭建一个SERVER { "_api": "【gotify推送】", "url": "[https://domain:port/message?token={token}](https://domain:port/message?token=%7Btoken%7D)", "data": "@${tempjsonpath}", "content_type": "Content-Type: application/json", "str_title_start": "【", "str_title_end": "】", "str_linefeed": "\n", "str_splitline": "\n\n", "str_space": " ", "str_tab": " ", "type": { "priority": "0", "title": ""${1}"", "message": ""${str_title_start}${1}${str_title_end}${str_splitline}${nowtime}${2}""
> 
> ```
> }
> ```
> 
> }

感谢，我试试

**Comment by YinHeng89** [comment]
我也贴一个 Gotify能用的

```
{
  "_api": "gotify",
  "_api": "【gotify】",
  "url": "https://url/message?token=apikey",
  "data": "@${tempjsonpath}",
  "content_type": "Content-Type: application/json",
  "str_title_start": " ",
  "str_title_end": "",
  "str_linefeed": "\\n",
  "str_splitline": "\\n\\n",
  "str_space": " ",
  "str_tab": "    ",
  "type": {
    "title": "\"${1}\"",
    "message": "\"${2}\"",
    "priority": "0"
  }
}
```
