### ISSUE TITLE
openwrt报废了， : Entry not found No page is registered at '/admin/services/serverchan'.

### ISSUE THREAD

**Issue by lozn00** [tty228/luci-app-wechatpush#247]
```
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing luci-i18n-wechatpush-zh-cn (git-23.169.53184-35dd92c) to root...
Configuring luci-i18n-wechatpush-zh-cn.
uci: Entry not found
```

No page is registered at '/admin/services/serverchan'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.

**Comment by tty228** [comment]
请使用 `opkg remove luci-app-wechatpush` 移除安装的插件
如果你使用的是 openwrt-18.06 及之前的版本（LuCI 18.06），请安装 v2.06.2 之前的版本
