### ISSUE TITLE
企业微信通知需要可信IP

### ISSUE THREAD

**Issue by han-xiaowang** [tty228/luci-app-wechatpush#249]
是否可以增加个代理，让搭建了Nginx反代的服务器转发。这样企业微信内可信IP填写VPS的IP就可以了

**Comment by tty228** [comment]
自行修改
https://github.com/tty228/luci-app-wechatpush/blob/f2d94830fa7e51ff193085156f603159a907fa59/root/usr/share/wechatpush/wechatpush#L156

如 `curl -x socks5://127.0.0.1:1024 --connect-timeout 30 -m 60 -X POST -H "$content_type" -d "$data" "${diyurl}"`

**Comment by tty228** [comment]
https://github.com/tty228/luci-app-wechatpush/commit/c750879e01d5417c9634da71abfd6cb872688914
待测试反馈

**Comment by wixxm** [comment]
> [c750879](https://github.com/tty228/luci-app-wechatpush/commit/c750879e01d5417c9634da71abfd6cb872688914) 待测试反馈

这个怎么测，我有国内的vps，可以配合测试，我也想用这个功能推送到微信号很方便

**Comment by wixxm** [comment]
> [c750879](https://github.com/tty228/luci-app-wechatpush/commit/c750879e01d5417c9634da71abfd6cb872688914) 待测试反馈

可以添加动态ip是可以收到推送 但是动态ip更换太麻烦。
