### ISSUE TITLE
【建议】希望可以支持Onebot

### ISSUE THREAD

**Issue by QwindF** [tty228/luci-app-wechatpush#250]
类似Uptime Kuma一样
![image](https://github.com/tty228/luci-app-wechatpush/assets/87116340/19a6b2e2-8e08-47eb-9414-521d1a3ed7db)

**Comment by tty228** [comment]
在现有的渠道可以正常使用的情况下，
暂不考虑新的推送渠道，实在太懒，还要做测试和调整格式，如果有需要请提交pr
