### ISSUE TITLE
immortalwrt23.05.4下占用较高

### ISSUE THREAD

**Issue by aenron** [tty228/luci-app-wechatpush#251]
版本信息：x86，immortalwrt23.05.4，wechatpush3.3.2
开启WeChatpush后cpu占用较高，导致风扇一直呼呼响，排查是进程 grep -q -w -i \n 导致的，关闭wechatpush后就没了。

**Comment by tty228** [comment]
尝试清空 /tmp/wechatpush/ 目录下的文件重新运行
另，没有具体日志无法分析

**Comment by aenron** [comment]
清空 /tmp/wechatpush/ 目录下的文件重新运行仍然无法解决问题。
没有日志是因为日志只有常规信息，里面没有相关有用内容。本地已经排查到是wechatpush运行时的“ grep -q -w -i ”命令导致一直占用较高。代码搜索后发现与此命令相关的只有检测设备在线、查询IP归属、设置黑名单等功能。
测试关闭主动探测功能，仍然持续有这个命令占用较大负载，继续关闭‘登录提醒’功能后，没这个命令进程在占用了，但是wechatpush占用还是有点高，
日志：2023-10-14 23:58:08 【初始化】start running...
2023-10-14 23:58:08 【info】开始后台更新 MAC 信息文件
2023-10-14 23:58:08 【info】未安装 wrtbwmon ，流量统计不可用
2023-10-14 23:58:25 【info】设备 MAC 信息文件下载成功，处理中
2023-10-14 23:58:27 【info】设备 MAC 信息文件处理完成
---------------------------------------------------------------------------------------
2023-10-14 23:59:02 【初始化】start running...
2023-10-14 23:59:02 【info】未安装 wrtbwmon ，流量统计不可用

**Comment by tty228** [comment]
我这边 x86，immortalwrt23.05.rc4 没有这个问题，怀疑是登录提醒配置信息有问题，"\n"为错误的换行符。应该是没做变量验证之类的
具体不知道是哪一个配置，检查一下配置，或者运行 `bash -x /usr/share/wechatpush/wechatpush t1` 看看有没有有用的信息

**Comment by tty228** [comment]
哦不对，你已经关掉相关功能了，关闭相关功能之后，占用大概有多少？

**Comment by aenron** [comment]
运行了一下“bash -x /usr/share/wechatpush/wechatpush t1”，这里可以排查到问题了：
+ echo '2023-10-15 10:58:32 【!!!】黑名单添加失败，IP 格式错误'
+ return
+ for ip_black in `cat ${ip_blacklist_path}|awk '{print $1}'`
+ add_ip_black '\n'
+ '[' '!' '\n' ']'
+ echo ''
+ grep -w -q '\n'
+ echo '\n'
+ grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$'
+ echo '\n'
+ grep -Eq '^([\da-fA-F0-9]{1,4}(:{1,2})){1,15}[\da-fA-F0-9]{1,4}$'
+ '[' -z '' ']'
++ date '+%Y-%m-%d %H:%M:%S'
+ echo '2023-10-15 10:58:32 【!!!】黑名单添加失败，IP 格式错误'
+ return
+ for ip_black in `cat ${ip_blacklist_path}|awk '{print $1}'`
+ add_ip_black '\n'
+ '[' '!' '\n' ']'
+ echo ''
+ grep -w -q '\n'
+ echo '\n'
+ grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$'
+ echo '\n'
+ grep -Eq '^([\da-fA-F0-9]{1,4}(:{1,2})){1,15}[\da-fA-F0-9]{1,4}$'
+ '[' -z '' ']'
++ date '+%Y-%m-%d %H:%M:%S'
+ echo '2023-10-15 10:58:32 【!!!】黑名单添加失败，IP 格式错误'
+ return
+ for ip_black in `cat ${ip_blacklist_path}|awk '{print $1}'`
+ add_ip_black '\n'
+ '[' '!' '\n' ']'
+ echo ''
+ grep -w -q '\n'
黑名单添加失败，IP 格式错误,这个原因导致的。排查下来应该是自动封禁-IP 黑名单列表里面数据根据提示保留一个回车时我直接写的“\n”导致的。
删除配置重新安装后该问题不再出现了，但是我重新安装后IP 黑名单列表里写个\n又无法复现了，估计是我某次写的时候配置错了，导致的问题。清空配置，重新安装后问题解决

**Comment by aenron** [comment]
问题解决，可以关闭issue了，多谢提供的排查方法。
