### ISSUE TITLE
设备列表显示建议

### ISSUE THREAD

**Issue by beck023** [tty228/luci-app-wechatpush#252]
1. 在线设备的列表里默认是怎么排序的呀?虽然可以点击一下鼠标根据需求排序,能不能改为默认按照IP地址从小到大排序呢?
2. 重启推送或者定时推送的信息里“在线设备”下的条目能不能也按照IP地址从小到达排序呢,有时候设备比较多的时候更容查找.
谢谢:)

**Comment by tty228** [comment]
1. 默认排序是基于连接时间，从新到旧
2. 因为我这边主要用途是偷窥领导在不在，曾经有过这个计划，但是打开编辑器之后懒癌复发，放弃了 >.<
