### ISSUE TITLE
关于推送请求次数的问题

### ISSUE THREAD

**Issue by lizhiwei8061** [tty228/luci-app-wechatpush#253]
我用的 pushplus，因为推送每天有次数限制，请求次数大概是收到的推送消息的三倍，正常不应该是一次请求对应一条消息嘛？

**Comment by tty228** [comment]
尝试手动发送，查询次数是否正确，推送服务未设置自动重试
没怎么用过 pushplus，不知道问题所在

**Comment by lizhiwei8061** [comment]
> 尝试手动发送，查询次数是否正确，推送服务未设置自动重试 没怎么用过 pushplus，不知道问题所在

次数确认过了，我大概算了  是不是勿扰模式 ，请求了没有推送导致的，如果是这样希望优化一下

**Comment by tty228** [comment]
免打扰时不会请求推送，勿扰时段只会挂起或跳过，勿扰信息只会跳过
且每次调用推送进程时，都会产生日志信息，请检查自身网络或日志信息

**Comment by lizhiwei8061** [comment]
> 免打扰时不会请求推送，勿扰时段只会挂起或跳过，勿扰信息只会跳过 且每次调用推送进程时，都会产生日志信息，请检查自身网络或日志信息

我昨天就是对应日志一条条的数的，能对应起来，但是和我实际收到的推送对应不起来

**Comment by tty228** [comment]
![微信截图_20231024103124](https://github.com/tty228/luci-app-wechatpush/assets/33397881/dfa4f4c6-ff39-4ee2-bbb3-ff09859191c8)

无法复现

**Comment by lizhiwei8061** [comment]
![Snipaste_2023-10-25_08-40-56](https://github.com/tty228/luci-app-wechatpush/assets/121220591/a4c499ef-f682-4c64-81bc-ec7f77bc594d)
![Snipaste_2023-10-25_08-42-09](https://github.com/tty228/luci-app-wechatpush/assets/121220591/8494272a-99d5-4f13-9ce3-c2e58e688735)
这是昨晚的日志，收到推送11条，请求次数76次，日志大概数了下70条，我不确定是哪里设置问题

**Comment by tty228** [comment]
接口限制
  为了让大家合理规范的使用微信渠道的消息推送，pushplus在单日请求次数上做了部分限制。每人每日可请求次数为200条，当大于200条的时候消息将不在推送。如继续发送请求，超过400次时，将会限制用户推送微信消息2天。如继续请求接口，将会受到更加严厉的惩罚。请及时减少推送请求，频率降低到正常范围内后才会自动解除限制。
  同时为了减少程序异常造成高频的请求，发送消息接口对请求频率做出了限制，1分钟内接收5次请求，超出的请求将不再推送。**另外对于相同的内容，1小时内限制发送3条。**

因 pushplus 推送内容中已自带时间，推送变量中并不包含设备连接时间，所以实际内容为相同，应该已经被服务器阻断
另外，对于夜间 iPhone 频繁离线的问题，建议在高级设置处自行调整超时设置

**Comment by lizhiwei8061** [comment]
> 接口限制   为了让大家合理规范的使用微信渠道的消息推送，pushplus在单日请求次数上做了部分限制。每人每日可请求次数为200条，当大于200条的时候消息将不在推送。如继续发送请求，超过400次时，将会限制用户推送微信消息2天。如继续请求接口，将会受到更加严厉的惩罚。请及时减少推送请求，频率降低到正常范围内后才会自动解除限制。   同时为了减少程序异常造成高频的请求，发送消息接口对请求频率做出了限制，1分钟内接收5次请求，超出的请求将不再推送。**另外对于相同的内容，1小时内限制发送3条。**
> 
> 因 pushplus 推送内容中已自带时间，推送变量中并不包含设备连接时间，所以实际内容为相同，应该已经被服务器阻断 另外，对于夜间 iPhone 频繁离线的问题，建议在高级设置处自行调整超时设置

好的了解了  谢谢
