### ISSUE TITLE
显示访问者的IP可以吗

### ISSUE THREAD

**Issue by yuanyiming** [tty228/luci-app-wechatpush#255]
大佬您好 我的软路由上了公网 我想让这个插件在telegram提示我有哪些IP进行了访问ssh和web 但是我发现这里面列出来的IP其实是软路由自己的内网IP而不是访问软路由的人的IP 请问如何在里面加上访问者的IP地址？谢谢大佬 期待您的回复
【istore】192.168.100.1 通过 web 登陆了路由器
----
2023-11-16 13:47:43
----
 登陆信息
    时间：     13:47:22
    设备 IP：     192.168.100.1

**Comment by tty228** [comment]
自行设置 NAT环回
