### ISSUE TITLE
设备MAC厂商信息下载失败

### ISSUE THREAD

**Issue by an-kang** [tty228/luci-app-wechatpush#256]
<img width="578" alt="image" src="https://github.com/tty228/luci-app-wechatpush/assets/35864786/a6a792df-562d-4d2e-bbc6-dd233846ca8d">
<img width="508" alt="image" src="https://github.com/tty228/luci-app-wechatpush/assets/35864786/82dedd19-6545-4dfe-b7a7-869635940bf3">
打开MAC设备信息数据库后，日志显示下载失败，想问下可以如何解决

**Comment by tty228** [comment]
这里偷懒了，重启会重新下载
