### ISSUE TITLE
请问和frpc如何结合使用才可以推送登录IP 为真实IP 呢

### ISSUE THREAD

**Issue by JuneZhao** [tty228/luci-app-wechatpush#257]
我这边是用的是这个版本

luci-app-wechatpush | git-24.273.44719-1ca28e0

，然后我通过frpc 来导流来自Internet 的流量，希望能够获取真实登录IP， 我这边frpc 是可以拿到这些IP 的，但是 这边推送的内容我发现都是127.0.0.1，我看登录IP的日志是不是都是从我的web server 的登录日志拿的？

2023/12/08 14:15:09 [D] [proxy_wrapper.go:255] [aadb7841b9218489] [xxx.Securehttps] start a new work connection, localAddr: x.x.x.x:56098 remoteAddr: x.x.x.x:5443

**Comment by tty228** [comment]
登录 IP 从 OpenWrt 的系统日志中读取，但 OpenWrt 的 uhttpd 无法读取反代等 IP 来源标签，如果有这个需求，请使用 nginx，大概
frpc 没怎么用过，不知道是不是跟反代类似，你可以试试做一下 Masquerading （IP 伪装）

**Comment by JuneZhao** [comment]
> 但 OpenWrt 的 uhttpd 无法读取反代等 IP 来源标签，如果有这个需求，请使用 nginx

好的， 想多问一下， OP 是否可以同时安装uhttpd和nginx 来服务web, 不确定会有什么冲突

**Comment by tty228** [comment]
建议你先试试在服务端防火墙设置好 IP 伪装
