### ISSUE TITLE
自动推送-免打扰提示信息问题

### ISSUE THREAD

**Issue by GOUKI9999** [tty228/luci-app-wechatpush#258]
提示前略，其中包括：    
    CPU 负载过高
    CPU 负载已连续  天  小时 超过预设   #没有按预想显示连续超过0天2小时
    接下来 -3600 秒 不再提示 #没有按预想显示接下来1小时不再提示
    当前负载：5.80

![image](https://github.com/tty228/luci-app-wechatpush/assets/11640942/f6c6d95f-c9c5-4ea8-bad8-5ee2ef6aa8fe)
设置如图，感觉好像是减法错误？
因为不完全理解超过阈值的持续时间累计逻辑，像我这样设置阈值超过2小时才提醒，并间隔1小时不再提醒应该并不是不合理的设置。
如果从12:00开始到14:00持续高于阈值，则在14:00发出，并在到15:00之前不再提醒；那么下一个提醒应该是15:00还是16:00呢，也就是是否在发出提示之后就重置了阈值持续时间累计？

**Comment by tty228** [comment]
（这个 bug 我还以为没人发现呢，沉迷魔兽一直没管）

**Comment by GOUKI9999** [comment]
魔，魔兽？

**Comment by tty228** [comment]
14:00 第一次推送通知后，实际上还是一直在检测，但是不推送通知，如果持续高负载，下一次发送通知会在 15:00 发送
检测超时基于 当前时间戳-上一次正常时的时间戳
免打扰时间为每次发送后记录时间戳，CD 结束后清除
