### ISSUE TITLE
您好，请问手动安装以后在管理界面找不到是，您知道是什么情况吗？我用的是eSir的x86-64固件

### ISSUE THREAD

**Issue by QQKR** [tty228/luci-app-wechatpush#259]
![image](https://github.com/tty228/luci-app-wechatpush/assets/152822962/a5432e21-23f6-44bf-a3ae-dddce4018207)

**Comment by nyaasuki** [comment]
同样的问题

**Comment by tty228** [comment]
v2.06.2 之后的版本不再支持 LuCI 18.06，如需编译，请使用 openwrt-18.06 分支，拉取源码时请使用 git clone -b openwrt-18.06 https://github.com/tty228/luci-app-wechatpush.git 命令

如需手动安装，请安装 v2.06.2

**Comment by QQKR** [comment]
按照您的提示已经解决，谢谢!

**Comment by QQKR** [comment]
是WeChat push的版本，下载旧版本安装就可以了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月30日 14:47 |
| 收件人 | tty228/luci-app-wechatpush ***@***.***> |
| 抄送人 | QQKR ***@***.***>,
State ***@***.***> |
| 主题 | Re: [tty228/luci-app-wechatpush] 您好，请问手动安装以后在管理界面找不到是，您知道是什么情况吗？我用的是eSir的x86-64固件 (Issue #259) |

表示不太懂 LuCI 18.06是openwrt的版本吗太高了还是
