### ISSUE TITLE
自动封禁的黑名单结尾会出现一些代码

### ISSUE THREAD

**Issue by RouRouX** [tty228/luci-app-wechatpush#260]
172.232.62.151 timeout 0
182.92.150.248 timeout 0\nHeader: family inet6 hashsize 1024 maxelem 65536 timeout 86400

![image](https://github.com/tty228/luci-app-wechatpush/assets/21698543/062f6802-c602-4b61-a134-a1070415b3f3)

我试图手动删除结尾处的乱码，如果有新的ip被封禁，结尾依然会出现。

**Comment by tty228** [comment]
这个应该是正则匹配得有问题，我这没有 ipset 的环境，当时写的时候没测试太久
运行一下
 `ipset list wechatpush_blacklist` 

还有 
`ipset list wechatpush_blacklist | grep "timeout"`
看一下返回值，我重新写一下正则

timeout 86400 这一行应该是 v6 的名单为空时错误的返回了值，但为什么不是 0 ，没看出来那里引发的问题，改的时候再找找吧

**Comment by RouRouX** [comment]
`
root@ImmortalWrt:~# ipset list wechatpush_blacklist
Name: wechatpush_blacklist
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 86400
Size in memory: 1064
References: 1
Number of entries: 9
Members:
14.103.42.2 timeout 0
45.132.194.18 timeout 0
222.77.96.4 timeout 0
113.125.70.92 timeout 0
60.170.105.154 timeout 0
172.234.120.193 timeout 0
172.105.90.105 timeout 0
172.232.62.151 timeout 0
182.92.150.248 timeout 0
root@ImmortalWrt:~# ipset list wechatpush_blacklist | grep "timeout"
Header: family inet hashsize 1024 maxelem 65536 timeout 86400
14.103.42.2 timeout 0
45.132.194.18 timeout 0
222.77.96.4 timeout 0
113.125.70.92 timeout 0
60.170.105.154 timeout 0
172.234.120.193 timeout 0
172.105.90.105 timeout 0
172.232.62.151 timeout 0
182.92.150.248 timeout 0

`
