### ISSUE TITLE
网络检测误判断为网络不通

### ISSUE THREAD

**Issue by OldCoding** [tty228/luci-app-wechatpush#261]
![image](https://github.com/tty228/luci-app-wechatpush/assets/85047508/a4379754-c3e9-47ab-b9f3-6af33e440b2a)
![image](https://github.com/tty228/luci-app-wechatpush/assets/85047508/77a06cd7-9f7e-474f-8fa3-bcd91243c650)
如图所示，起点网站的http状态码返回的是202，脚本中没有这一情况的判断，导致误判断为网络不通

**Comment by tty228** [comment]
先临时修复吧
https://github.com/tty228/luci-app-wechatpush/commit/28fb65ad06e37e0f55447e85865939e29db52d78

**Comment by harrison-guo-chn** [comment]
希望把这个修改提交到18.06的分支里面，因为18.06的文件没有修改这个值，会一直提示网络不通
