### ISSUE TITLE
频繁报错网络不通和网络恢复正常

### ISSUE THREAD

**Issue by wannycoco** [tty228/luci-app-wechatpush#263]
报错问题如标题

系统 iStoreOS x86，确认过 curl 等依赖都有正常安装，网络正常，检测的几个网址163，qq，豆瓣等也能正常访问，但还是不停打印网络不通停止检测和网络恢复正常的日志，求助大佬该如何解决

**Comment by tty228** [comment]
https://github.com/tty228/luci-app-wechatpush/issues/261
