### ISSUE TITLE
求助，群晖有类似功能的套件吗？

### ISSUE THREAD

**Issue by axinhouzilaoyue** [tty228/luci-app-wechatpush#266]

**Comment by GOUKI9999** [comment]
群晖两个方案一个是控制面板里面的-通知设置-短信-自己写一下http指令，把参数拼进去就行，基本都能实现效果，但只能通过规则中的事件trigger发送，另一个是用任务计划（crontab like）运行自己的脚本，我目前就是通过群晖威联通的类似功能和openwrt下的 luci-wechatpush形成定期的设备情况汇总一起发送到指定渠道。
