### ISSUE TITLE
3.4.2在op 23.05上有几率定时推送时推送内容不正常

### ISSUE THREAD

**Issue by xianren78** [tty228/luci-app-wechatpush#272]
系统 op 23.05 （Immortal） 运行在PVE虚拟机中
三台路由器均有类似表现，一般一天不定时有那么一两次（每小时推送一次）。
以下是正常的和不正常的表现，设备列表都是正常的。
猜测：是不是全球互联那个测试失败导致其他项目没有正常获取？
印象中原来在lean op中用老版本没出现过这个问题。

![QQ截图20240422161702](https://github.com/tty228/luci-app-wechatpush/assets/26913311/68e5fe3e-ce5a-48ca-bf34-79e95f521f7f)
![QQ截图20240422161731](https://github.com/tty228/luci-app-wechatpush/assets/26913311/63b4c1bb-a959-4c18-9e0b-f38c68e54871)

**Comment by tty228** [comment]
这个是 v2.07.4 中优化了定时推送时间之后，不知道跟后面的哪次修改出了冲突
之前的定时推送时间太久了，Web 上点击的话，会被浏览器超时拒绝，所以才有了这次修改
https://github.com/tty228/luci-app-wechatpush/releases/tag/v2.07.4
还没来得及查，上次粗略的看了一下，感觉上像是生成的临时文件被清空了导致，但是因为不好复现，所以没看出来问题出在哪里

**Comment by xianren78** [comment]
![IMG_20240502_090002](https://github.com/tty228/luci-app-wechatpush/assets/26913311/14e557c4-95a4-4fa0-8bb3-84dbcf17b66f)
整好碰到一次错误，后来看了一下，后台运行的程序每两分钟清空一次$output_dir，这个如果整好和send重合的话，可能会删除send写入的数据。如果在send的时候加锁，然后wait_and_cat删除的时候检测一下应该可以避免这个问题。

**Comment by GOUKI9999** [comment]
/usr/share/wechatpush/wechatpush send
cat: can't open '/sys/block/root/device/model': No such file or directory
cat: can't open '/sys/block/ubi0_/device/model': No such file or directory
我也遇到了类似问题，表现也是只有一台升级到最新opwrt的自动推送不正常，而最奇怪的是点击手动则完全正常

尝试手动执行crontab 
/usr/share/wechatpush/wechatpush send
cat: can't open '/sys/block/root/device/model': No such file or directory
ct: can't open '/sys/block/ubi0_/device/model': No such file or directory
此时日志正常 
2024-05-06 12:09:13 【定时数据】创建定时任务
2024-05-06 12:09:17 【telegram】定时推送任务完成
但发送不出去

而更令我困惑的问题是，自动执行的日志通常为crul返回错误如35等，环境方面反复测试过并保持和其他设备配置一致，始终还是会有定时推送失败的问题，目前没什么办法，而且觉得似乎问题不止一处

**Comment by xianren78** [comment]
> 环境：斐讯K3 版本 git-25.030.44721-092e35e 分支: 23.05-SNAPSHOT 内核: 5.15.155
> 
> 问题，定时推送几乎全部会失败，手动执行则几乎完全没有问题
> 
> 我也遇到了类似问题，表现也是只有一台K3不正常，另一个使用相同版本，相同编译来源的下载宝则表现正常，**而最奇怪的是点击手动则完全正常**，包含基本设置的“发送测试”和定时推送的“手动发送”，这两个几乎从没有遇到过失败，除非是网络出现问题。
> 
> 尝试手动执行crontab /usr/share/wechatpush/wechatpush send cat: can't open '/sys/block/root/device/model': No such file or directory ct: can't open '/sys/block/ubi0_/device/model': No such file or directory 此时日志正常 2024-05-06 12:09:13 【定时数据】创建定时任务 2024-05-06 12:09:17 【telegram】定时推送任务完成 **但发送不出去**
> 
> 而更令我困惑的问题是，K3自动执行的日志通常为curl返回错误如35等，用debug提供的curl指令测试也正常可以收到 环境方面反复测试过并保持和其他设备配置一致，始终还是会有定时推送失败的问题，目前没什么办法，而且觉得似乎问题不止一处
> 
> **同一问题在同版本的下载宝上并没有出现**

你这个问题和我的不一样。你描述的问题其实是有矛盾的，就是按钮执行和/usr/share/wechatpush/wechatpush send这样发送效果是一样的，理论上不会出现你说的按钮执行都没问题， 但是terminal运行出现发生成功但是收不到。
另外一点，K3自动执行的日志通常为curl返回错误如35等，这个错误可以通过更改定时发送时间到01:02 02:02这种时间来解决。原来wechatpush默认的都是整点发送，疑似会有很大概率出现发送失败。修改位置在下图所示位置，我改成整点延后2分钟发送了。
![cron](https://github.com/tty228/luci-app-wechatpush/assets/26913311/5b02a130-8061-4fda-a1cd-5879abd91710)

**Comment by GOUKI9999** [comment]
> 你这个问题和我的不一样。你描述的问题其实是有矛盾的，就是按钮执行和/usr/share/wechatpush/wechatpush send这样发送效果是一样的，理论上不会出现你说的按钮执行都没问题， 但是terminal运行出现发生成功但是收不到。 另外一点，K3自动执行的日志通常为curl返回错误如35等，这个错误可以通过更改定时发送时间到01:02 02:02这种时间来解决。原来wechatpush默认的都是整点发送，疑似会有很大概率出现发送失败。修改位置在下图所示位置，我改成整点延后2分钟发送了。修改后/etc/init.d/wechatpush restart 然后crontab -l看修改是否成功。 ![cron](https://private-user-

首先，多谢您的回复，我说的是我的问题“类似”，没有说**一样**，其次，按钮执行和发送我并不确定是否一个脚本的**完全相同的参数**，而且我反复确认了日志情况和发送结果，确实是一直存在手动执行无法发送成功的问题，如果存在矛盾，想来是逻辑上的矛盾（例如按钮的参数和手动send参数不完全相同），而非我叙述上的矛盾；最后非常感谢您热心提出的方案，不过我目前的需求就是“整点发送”以保证和其他几个设备发送到同一个客户端的时间的尽可能同步（目前在10秒以内，通常不高于5秒），因此延迟时间的方案不太适合我，而且同样使用整点的其他几个设备也没有出现问题（含一个软路由，一个下载宝），所以我想“整点”本身不是一个问题，也不太想用这个方案，我之前考虑的是提前一分钟。

**Comment by xianren78** [comment]
> > 你这个问题和我的不一样。你描述的问题其实是有矛盾的，就是按钮执行和/usr/share/wechatpush/wechatpush send这样发送效果是一样的，理论上不会出现你说的按钮执行都没问题， 但是terminal运行出现发生成功但是收不到。 另外一点，K3自动执行的日志通常为curl返回错误如35等，这个错误可以通过更改定时发送时间到01:02 02:02这种时间来解决。原来wechatpush默认的都是整点发送，疑似会有很大概率出现发送失败。修改位置在下图所示位置，我改成整点延后2分钟发送了。修改后/etc/init.d/wechatpush restart 然后crontab -l看修改是否成功。 ![cron](https://private-user-
> 
> 首先，多谢您的回复，我说的是我的问题“类似”，没有说**一样**，其次，按钮执行和发送我并不确定是否一个脚本的**完全相同的参数**，而且我反复确认了日志情况和发送结果，确实是一直存在手动执行无法发送成功的问题，如果存在矛盾，想来是逻辑上的矛盾（例如按钮的参数和手动send参数不完全相同），而非我叙述上的矛盾；最后非常感谢您热心提出的方案，不过我目前的需求就是“整点发送”以保证和其他几个设备发送到同一个客户端的时间的尽可能同步（目前在10秒以内，通常不高于5秒），因此延迟时间的方案不太适合我，而且同样使用整点的其他几个设备也没有出现问题（含一个软路由，一个下载宝），所以我想“整点”本身不是一个问题，也不太想用这个方案，我之前考虑的是提前一分钟。

实际上我没看出来类似点在哪儿，如果有问题请另开issue

**Comment by GOUKI9999** [comment]
> 实际上我没看出来类似点在哪儿，我说不一样的意思是你这个问题最好另开issue，而不应该接在这个issue下，可能会被owner忽略，仅此而已，不需要这么敏感

我看意思您有两个理解和我不一样，
1，一个标题比较泛泛的issue下应该精确讨论一个极为具体的问题，甚至于问题有类似但不一样的都不宜参与讨论；
（在这个议题下，就是“该推送不正常必须是由output被定时清理所致”才能讨论，其他如curl参数设置或其他原因导致的推送不正常就不能讨论）
2，一样和不一样由issue提出者判断，是不是需要另立issue同上

我看了一下，这个luci还叫serverchan的时候我就是一直在提issue的，而且经常一个issue下提出不止一个问题或者扩展到其他问题，我看到的就是owner从来都态度很好地和我沟通并尝试解决。
#226 #230 #232 #237 #240
所以我不知道什么时候有的这种社区规则，我尝试和owner的讨论被人（强行参与）并阻止和要求另立issue。
其次我觉得您以后可以直接拿出“谁让你讨论无关问题了，这是我的issue，无关人请立刻离开”这种圈地的明确态度而不用这么绕弯子，虽然我不知道您这么作的底气是哪里来的，但我尊重您的意见。
如果言语中有什么冒犯，那可能就是我要表达的态度，仅此而已，不需要敏感，见谅。

**Comment by xianren78** [comment]
> > 实际上我没看出来类似点在哪儿，我说不一样的意思是你这个问题最好另开issue，而不应该接在这个issue下，可能会被owner忽略，仅此而已，不需要这么敏感
> 
> 我看意思您有两个理解和我不一样， 1，一个标题比较泛泛的issue下应该精确讨论一个极为具体的问题，甚至于问题有类似但不一样的都不宜参与讨论； （在这个议题下，就是“该推送不正常必须是由output被定时清理所致”才能讨论，其他如curl参数设置或其他原因导致的推送不正常就不能讨论） 2，一样和不一样由issue提出者判断，是不是需要另立issue同上
> 
> 我看了一下，这个luci还叫serverchan的时候我就是一直在提issue的，而且经常一个issue下提出不止一个问题或者扩展到其他问题，我看到的就是owner从来都态度很好地和我沟通并尝试解决。 #226 #230 #232 #237 #240 所以我不知道什么时候有的这种社区规则，我尝试和owner的讨论被人（强行参与）并阻止和要求另立issue，实际上就算我离题万里说了不相关的话，正常操作也是点hide-off topic。 其次我觉得您以后可以直接拿出“谁让你讨论无关问题了，这是我的issue，无关人请立刻离开”这种圈地的明确态度而不用这么绕弯子，虽然我不知道您这么作的底气是哪里来的，但我尊重您的意见。 如果言语中有什么冒犯，那可能就是我要表达的态度，仅此而已，不需要这么敏感，见谅。

没人否定你的贡献，但是你已经在off-topic了，而且太远了。自大且不懂得尊重人，请自便。这issue本身你就是不请自来的。你所谓的套路与我的issue风马牛不相及。

**Comment by GOUKI9999** [comment]
> > > 实际上我没看出来类似点在哪儿，我说不一样的意思是你这个问题最好另开issue，而不应该接在这个issue下，可能会被owner忽略，仅此而已，不需要这么敏感
> > 
> > 
> > 我看意思您有两个理解和我不一样， 1，一个标题比较泛泛的issue下应该精确讨论一个极为具体的问题，甚至于问题有类似但不一样的都不宜参与讨论； （在这个议题下，就是“该推送不正常必须是由output被定时清理所致”才能讨论，其他如curl参数设置或其他原因导致的推送不正常就不能讨论） 2，一样和不一样由issue提出者判断，是不是需要另立issue同上
> > 我看了一下，这个luci还叫serverchan的时候我就是一直在提issue的，而且经常一个issue下提出不止一个问题或者扩展到其他问题，我看到的就是owner从来都态度很好地和我沟通并尝试解决。 #226 #230 #232 #237 #240 所以我不知道什么时候有的这种社区规则，我尝试和owner的讨论被人（强行参与）并阻止和要求另立issue，实际上就算我离题万里说了不相关的话，正常操作也是点hide-off topic。 其次我觉得您以后可以直接拿出“谁让你讨论无关问题了，这是我的issue，无关人请立刻离开”这种圈地的明确态度而不用这么绕弯子，虽然我不知道您这么作的底气是哪里来的，但我尊重您的意见。 如果言语中有什么冒犯，那可能就是我要表达的态度，仅此而已，不需要这么敏感，见谅。
> 
> 没人否定你的贡献，但是你已经在off-topic了，而且太远了。自大且不懂得尊重人，请自便。这issue本身你就是不请自来的。你所谓的套路与我的issue风马牛不相及。

**Comment by GOUKI9999** [comment]
> > > > 实际上我没看出来类似点在哪儿，我说不一样的意思是你这个问题最好另开issue，而不应该接在这个issue下，可能会被owner忽略，仅此而已，不需要这么敏感
> > > 
> > > 
> > > 我看意思您有两个理解和我不一样， 1，一个标题比较泛泛的issue下应该精确讨论一个极为具体的问题，甚至于问题有类似但不一样的都不宜参与讨论； （在这个议题下，就是“该推送不正常必须是由output被定时清理所致”才能讨论，其他如curl参数设置或其他原因导致的推送不正常就不能讨论） 2，一样和不一样由issue提出者判断，是不是需要另立issue同上
> > > 我看了一下，这个luci还叫serverchan的时候我就是一直在提issue的，而且经常一个issue下提出不止一个问题或者扩展到其他问题，我看到的就是owner从来都态度很好地和我沟通并尝试解决。 #226 #230 #232 #237 #240 所以我不知道什么时候有的这种社区规则，我尝试和owner的讨论被人（强行参与）并阻止和要求另立issue，实际上就算我离题万里说了不相关的话，正常操作也是点hide-off topic。 其次我觉得您以后可以直接拿出“谁让你讨论无关问题了，这是我的issue，无关人请立刻离开”这种圈地的明确态度而不用这么绕弯子，虽然我不知道您这么作的底气是哪里来的，但我尊重您的意见。 如果言语中有什么冒犯，那可能就是我要表达的态度，仅此而已，不需要这么敏感，见谅。
> > 
> > 
> > 没人否定你的贡献，但是你已经在off-topic了，而且太远了。自大且不懂得尊重人，请自便。这issue本身你就是不请自来的。你所谓的套路与我的issue风马牛不相及。

“我的issue”，“仅此而已，不用这么敏感”，噗。祝您往后圈地发展顺利，在自己的一亩三分地里大显雄威。

**Comment by xianren78** [comment]
> > > > > 实际上我没看出来类似点在哪儿，我说不一样的意思是你这个问题最好另开issue，而不应该接在这个issue下，可能会被owner忽略，仅此而已，不需要这么敏感
> > > > 
> > > > 
> > > > 我看意思您有两个理解和我不一样， 1，一个标题比较泛泛的issue下应该精确讨论一个极为具体的问题，甚至于问题有类似但不一样的都不宜参与讨论； （在这个议题下，就是“该推送不正常必须是由output被定时清理所致”才能讨论，其他如curl参数设置或其他原因导致的推送不正常就不能讨论） 2，一样和不一样由issue提出者判断，是不是需要另立issue同上
> > > > 我看了一下，这个luci还叫serverchan的时候我就是一直在提issue的，而且经常一个issue下提出不止一个问题或者扩展到其他问题，我看到的就是owner从来都态度很好地和我沟通并尝试解决。 #226 #230 #232 #237 #240 所以我不知道什么时候有的这种社区规则，我尝试和owner的讨论被人（强行参与）并阻止和要求另立issue，实际上就算我离题万里说了不相关的话，正常操作也是点hide-off topic。 其次我觉得您以后可以直接拿出“谁让你讨论无关问题了，这是我的issue，无关人请立刻离开”这种圈地的明确态度而不用这么绕弯子，虽然我不知道您这么作的底气是哪里来的，但我尊重您的意见。 如果言语中有什么冒犯，那可能就是我要表达的态度，仅此而已，不需要这么敏感，见谅。
> > > 
> > > 
> > > 没人否定你的贡献，但是你已经在off-topic了，而且太远了。自大且不懂得尊重人，请自便。这issue本身你就是不请自来的。你所谓的套路与我的issue风马牛不相及。
> 
> “我的issue”，“不请自来““仅此而已，不用这么敏感”，噗。祝您往后圈地发展顺利，在自己的一亩三分地里大显雄威。

该去哪儿玩泥巴去哪儿玩泥巴，谁有空理你，傻鸟。。。
