### ISSUE TITLE
3.4.2   发送测试失败   第一次收到了    再然后就收不到了，重启也收不到

### ISSUE THREAD

**Issue by qq1316237299** [tty228/luci-app-wechatpush#273]
![image](https://github.com/tty228/luci-app-wechatpush/assets/42686656/fe0a30f4-a1a5-48a8-a229-8e66511d7751)
![image](https://github.com/tty228/luci-app-wechatpush/assets/42686656/eee904d1-3da4-45e6-8ad4-cadf462e7d4c)

**Comment by tty228** [comment]
“请勿频繁推送相同内容”
