### ISSUE TITLE
企业微信推送为什么强制填写可信IP地址呢？

### ISSUE THREAD

**Issue by liyuhaolol** [tty228/luci-app-wechatpush#274]
最近我重新编译OP，我发现企业微信要填写的东西发生了很大变化。我以前使用的版本是serverchan-1.86版本。我企业微信也是18年注册的，此后再也没动过。目前推送功能一切正常。所以我这好像并不需要可信IP地址吧？但是咱们的功能里，可信IP地址变成了必填项。这让我怎么用新版本的wechatpush呢？而且我发现老版本要求的corpid;userid;agentid;corpsecret;mediaid中的mediaid，新版本也不要传了，变成了一个本地图片？这不是重点，我主要还是想知道如果我这种注册企业微信非常早的用户，我到底怎么使用新版wechatpush设置企业微信？难道非得让我登录到企业微信设置个可信IP自我阉割一刀？

**Comment by tty228** [comment]
不是必填项，请更新版本
