### ISSUE TITLE
定时推送失败（手动可以），以及硬盘信息错误

### ISSUE THREAD

**Issue by GOUKI9999** [tty228/luci-app-wechatpush#275]
问题更新到0508

环境：斐讯K3 版本 git-25.030.44721-092e35e
分支: 23.05-SNAPSHOT
内核: 5.15.155

问题，定时推送几乎全部会失败，手动执行则几乎完全没有问题

目前表现也是只有一台K3不正常，另一个使用相同版本，相同编译来源的下载宝则表现正常，而最奇怪的是点击luci里的手动则完全正常，包含基本设置的“发送测试”和定时推送的“手动发送”，这两个几乎从没有遇到过失败，除非是网络出现问题。

尝试手动执行crontab
/usr/share/wechatpush/wechatpush send
cat: can't open '/sys/block/root/device/model': No such file or directory
ct: can't open '/sys/block/ubi0/device/model': No such file or directory_
此时日志正常 (这两行已经看了，应该是取挂载的储存设备名称，错误也就是对应信息里名称为空不影响发送才对）

2024-05-06 12:09:13 【定时数据】创建定时任务
2024-05-06 12:09:17 【telegram】定时推送任务完成
但发送不出去

而更令我困惑的问题是，K3自动执行的日志通常为curl返回错误如35等，终端debug提供的curl指令测试也正常可以收到
环境方面反复测试过并保持和其他设备配置一致，始终还是会有定时推送失败的问题，目前没什么办法，而且觉得似乎问题不止一处

同一问题在同版本的下载宝上并没有出现

补充：试图解决出现空硬盘名和send报错的问题，但在安装lsblk之后变奇怪了，我看了一下
root@FX_K3:~# lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
sda 8:0 1 977.5M 0 disk
└─sda1 8:1 1 976.4M 0 part /mnt/sda1
mtdblock0 31:0 0 512K 1 disk
mtdblock1 31:1 0 1M 0 disk
mtdblock2 31:2 0 2.5M 1 disk
mtdblock3 31:3 0 124M 0 disk
mtdblock4 31:4 0 4M 1 disk
mtdblock5 31:5 0 120M 0 disk
zram0 253:0 0 165M 0 disk [SWAP]
ubiblock0_0 254:0 0 45.9M 0 disk /rom

按脚本逻辑 lsblk 2>/dev/null | awk '$NF=="disk" {print $1}' | sort -u
应该为
mtdblock0
mtdblock1
mtdblock2
mtdblock3
mtdblock4
mtdblock5
sda

则终端send 日志为
cat: can't open '/sys/block/mtdblock0/device/model': No such file or directory
cat: can't open '/sys/block/mtdblock1/device/model': No such file or directory
cat: can't open '/sys/block/mtdblock2/device/model': No such file or directory
cat: can't open '/sys/block/mtdblock3/device/model': No such file or directory
cat: can't open '/sys/block/mtdblock4/device/model': No such file or directory
cat: can't open '/sys/block/mtdblock5/device/model': No such file or directory

结果打印为若干空“硬盘名称”
硬盘名称：
硬盘名称：
硬盘名称：
硬盘名称：
硬盘名称：
硬盘名称：
硬盘名称：Cruzer Micro_977.5M
空间使用：sda1: 49%

另一台设备，lsblk结果
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
sda 8:0 1 963M 0 disk /mnt/sda
mtdblock0 31:0 0 192K 1 disk
mtdblock1 31:1 0 64K 1 disk
mtdblock2 31:2 0 64K 1 disk
mtdblock3 31:3 0 15.7M 0 disk
mtdblock4 31:4 0 2.9M 1 disk
mtdblock5 31:5 0 12.8M 1 disk /rom
mtdblock6 31:6 0 2.4M 0 disk /mnt/mtdblock6
mmcblk0 179:0 0 1.9G 0 disk
└─mmcblk0p1 179:1 0 1.9G 0 part /
zram0 253:0 0 81M 0 disk [SWAP]

lsblk 2>/dev/null | awk '$NF=="disk" {print $1}' | sort -u
输出少了第一行的U盘，因为最后字符是挂载点而不是type

手动执行send，无报错信息，但结果中没有任何硬盘信息

**Comment by xianren78** [comment]
我也有个类似问题： 系统 op 23.05 （Immortal） 运行在PVE虚拟机中
三台路由器均有类似表现，一般一天不定时有那么一两次（每小时推送一次）。
以下是正常的和不正常的表现，设备列表都是正常的。
猜测：是不是全球互联那个测试失败导致其他项目没有正常获取？
印象中原来在lean op中用老版本没出现过这个问题。

![image](https://github.com/tty228/luci-app-wechatpush/assets/26913311/dba84841-77fa-4db0-96d3-11b10a9fdde5)
![image](https://github.com/tty228/luci-app-wechatpush/assets/26913311/13d0d794-f718-4cdf-8d25-cc7de847938c)
