### ISSUE TITLE
黑名单列表不能删除

### ISSUE THREAD

**Issue by gtjyj** [tty228/luci-app-wechatpush#278]
经过测试删除黑名单列表（全部清空打一个回车保存）不能立即生效,要关闭拉黑功能,然后测试设备才能重新打开

另外为什么我生成的黑名单是这样的格式,不是timeout xxxxx:

106.89.26.188 expires 50m43s765ms \n

**Comment by tty228** [comment]
不是不能立即生效，而是不会生效，原因是上次改为实时拉黑之后漏掉了
不过现在也不能实时生效，因为实时的话，需要监听文件变化，感觉没必要
另外多余的回车已经在 https://github.com/tty228/luci-app-wechatpush/commit/22012303ef503b86f30d9d0e4368262a3fe07bb4 中修复了
