### ISSUE TITLE
在Luci里找不到wechatpush

### ISSUE THREAD

**Issue by 1WuNeiGui** [tty228/luci-app-wechatpush#280]
Immortalwrt23.05版本，在package里拉取了源码，但是make menuconfig时，在Luci里却找不到这个插件，请问这是为啥

**Comment by Ma-Huan2001** [comment]
重新拉取后可以在菜单里找到了

**Comment by Ma-Huan2001** [comment]
还是有问题，在纯ubuntu系统中，可以找到，但是在wsl中就找不到

**Comment by tty228** [comment]
没有 wsl 环境，不清楚
