### ISSUE TITLE
启动后，不断请求  douban.com，   qidian.com ， 163.com， qq.com 等dns， 请问是为了检测网络么

### ISSUE THREAD

**Issue by xiebaiyuan** [tty228/luci-app-wechatpush#282]
版本是： 3.3.2 
启动后，不断请求  douban.com，   qidian.com ， 163.com， qq.com 等dns， 请问是为了检测网络么

关闭插件后就没有了。 安装后就重新出现。

**Comment by tty228** [comment]
嗯对，master 编译的话，检测的是
http://connect.rom.miui.com/generate_204
http://wifi.vivo.com.cn/generate_204
http://connectivitycheck.platform.hicloud.com/generate_204
http://www.apple.com/library/test/success.html
