### ISSUE TITLE
请问如何把Cron Job定时任务的运行结果通过调用wechatpush发送通知

### ISSUE THREAD

**Issue by mikal** [tty228/luci-app-wechatpush#284]
使用的版本如下：luci-app-serverchan | 2.01.4-9
请问如何将Cron Job定时运行的脚本结果，通过调用本插件发送通知？  例如以下这个每天3点半运行的sh脚本，现在是将运行结果发送给日志。谢谢！
```
30 3 * * * /etc/xxx/run.sh | logger
```

**Comment by tty228** [comment]
没有预留这个功能，虽然实际上 json 文件中

`"_data": "生成的 json 文件路径，一般不需要改，如 api 不支持 json，请参考 serverchan 推送接口",`

https://github.com/tty228/luci-app-wechatpush/blob/v2.01.4/root/usr/bin/serverchan/api/diy.json#L8

这个就是要发送的内容的路径

**Comment by tty228** [comment]
简单一点的方法，你可以先准备好要推送的内容，格式大约如下
{
  "text": "<b>【i3-5015U】发送测试：</b>\n----\n2024-07-08 13:28:14\n----\n<b>内容1</b>\n    设备1\n    设备2\n----\n<b>内容2</b>\n    设备3\n    设备4",
  "chat_id": "******",
  "parse_mode": "HTML"
}

然后打开你使用的推送方式 API 文件，如 `/usr/share/wechatpush/api/telegram.json`，复制一份，并将新文件中 "data": "@${tempjsonpath}" 更换为生成的 json 推送内容实际地址
如：
"data": "@/tmp/wechatpush/debug_send_data"

然后：
`uci set wechatpush.config.jsonpath='/usr/share/wechatpush/api/telegram2.json'`
`uci commit wechatpush`
`bash /usr/share/wechatpush/wechatpush test`

就可以狸猫换太子，把推送测试的内容替换成你要的内容，并发送了

**Comment by mikal** [comment]
好的，谢谢作者大大的解答，我尝试了下，没能收到自定义路径json的测试tg通知，请大佬再麻烦分析下问题何在？  
cp '/usr/bin/serverchan/api/telegram.json' '/usr/bin/serverchan/api/telegram3.json'   
复制tg的json文件，然后修改了其中第六行为"data": "@/tmp/serverchan/send_data1",   
新增了文件/tmp/serverchan/send_data1，其中的内容如下：  
```
{
  "text": "<b>...r5s-501...</b>\n----\n2024-07-08 13:28:14\n----\n<b>......1</b>\n    ......1\n    ......2\n----\n<b>......2</b>\n    ......3\
  "chat_id": "*******", ##具体的chat_id数字
  "parse_mode": "HTML"
}
~
```
接着运行以下的测试命令，在网页端luci界面的日志看到创建定时任务，定时任务推送完成。但是实际***在手机端***并没有收到测试的通知。
```
uci set serverchan.serverchan.jsonpath='/usr/bin/serverchan/api/telegram3.json'
uci commit serverchan
bash /usr/bin/serverchan/serverchan test
```
此时在网页端的配置界面，推送模式变成了微信Server酱，若再把serverchan.serverchan.jsonpath切换回默认值后，网页版的推送模式又会显示正常的TG。

**Comment by tty228** [comment]
你要使用你原本的推送方式做修改，因为配置信息不是全都在 json 里面，如果使用 Server酱 的话，直接把要发送的字符串传入/usr/share/wechatpush/api/serverchan.json 文件中的 "data" 字段就行了，记得 html 转义

**Comment by mikal** [comment]
> 你要使用你原本的推送方式做修改，因为配置信息不是全都在 json 里面，如果使用 Server酱 的话，直接把要发送的字符串传入/usr/share/wechatpush/api/serverchan.json 文件中的 "data" 字段就行了，记得 html 转义
谢谢作者大大的快速响应，我还是要用tg推送通知。若是用以下命令，指向tg的默认json文件，发送tg的测试通知是ok的。
`uci set serverchan.serverchan.jsonpath='/usr/bin/serverchan/api/telegram.json'`
我将该文件复制为telegram3.json，并作出了以下的修改，还是发送tg测试失败，请问json文件，还有哪里需要再修改？  再次叩谢 
```
将第5行，${tg_token}替换为token的具体值，即"url": "https://api.telegram.org/botxxxxxxxxxxxxxxx/sendMessage",
将第17行，${chat_id}替换为具体的ID值，即"chat_id":"\"12345678\"",
```

**Comment by tty228** [comment]
没仔细看，网页上显示 微信Server酱是因为发送结束之后，没用下面的命令还原设置，网页上就显示了默认的设置
```
uci set serverchan.serverchan.jsonpath='/usr/bin/serverchan/api/telegram.json'
uci commit serverchan
```

如果是 tg 的推送的话，就修改
"data": "@/tmp/wechatpush/debug_send_data"
指向的文件路径就行了，别的不需要修改，会自己从程序的配置中读取

![图片](https://github.com/tty228/luci-app-wechatpush/assets/33397881/30f959b4-3813-4631-87bd-fa53d2d4a688)

![图片](https://github.com/tty228/luci-app-wechatpush/assets/33397881/df8a958c-67fc-4fd5-8108-45c1da86e70b)

主要是你用的旧版本，就算我更新了代码你也没法用，只能这样了

**Comment by tty228** [comment]
另外，发送失败的原因有两个
1. chat_id 的值一般应该是 -*****，即 -12345 这样的值
2. 如果直接将值写到文件中，是不需要斜杠的，斜杠是用于将变量转义，所以应是

`"chat_id":"-12345678", `

**Comment by mikal** [comment]
感恩作者的快速回复，我也发觉了是chat_id的填写有问题，就做了如下修改。
![Image_20240709005](https://github.com/tty228/luci-app-wechatpush/assets/59812419/21e174aa-a70b-4736-92d9-409d35d5df70)
/tmp/serverchan/data1的文件内容如下 
![Image_20240709004](https://github.com/tty228/luci-app-wechatpush/assets/59812419/f5ae6c17-8eac-40f6-887b-4efb9e4a808f)
然后，再次测试tg通知任务，如下图，在手机端TG还是没有能收到...lol，看看还能否再挽救下？
![image](https://github.com/tty228/luci-app-wechatpush/assets/59812419/febe4dad-10da-4755-94d9-13297f9cea6c)

**Comment by tty228** [comment]
你可以使用 `sh -x /usr/share/serverchan/serverchan send` 或是
`curl -X POST -H "Content-Type: application/json" -d "@/tmp/serverchan /data1" "https://api.telegram.org/bot******/sendMessage"`

手动发送查看一下返回值

**Comment by mikal** [comment]
非常感谢作者大大的耐心讲解，问题解决了，是测试发送的json文件格式问题，另外我的chat_id值应是”12345678“（没有带”-“），更正如下即可：   
```
{
  "text": "<b>【i5】发送测试：</b>\n----\n2024-07-08 13:28:14\n----\n<b>内容1</b>\n    设备1\n    设备2\n----\n<b>内容2</b>\n    设备3\n    设备4",
  "chat_id": "12345678",
  "parse_mode": "HTML"
}
```
