### ISSUE TITLE
今年更新的版本在设备上线提醒方面好像有点问题

### ISSUE THREAD

**Issue by sunyen** [tty228/luci-app-wechatpush#293]
x86的OpenWrt，
一开始自带的是serverchan用着所有功能都是没问题的，
上个月底看到今年更新了版本，然后直接更新到最新版本了，
随后出现了新设备上线之后下不会推送通知的情况，
但是web登录、ssh登录还有定时推送这些都是没问题的。
后来降级到去年的3.4.2的话，功能基本都正常了，
但还是存在新设备上线之后，设备上线的消息好像过了5分钟左右才会推送过来。
今晚突然看到大佬前两天又更新了，所以尝试更新到最新的3.5.6之后，还是不会推送设备上线的通知，另外更新到3.5.6还会出现web登录和ssh登录会一次推送两条同样的消息。

**Comment by tty228** [comment]
设备上线延迟应该跟加入的功能有关（设备列表检查 IP 是否可以 http:// 访问、netbios 查询主机名、失效的文件锁修复）
所以设备较多的话，每一轮的检查时间应该是比之前久，如果设备较多，会造成推送时间延迟
如果设备性能较好，把最大并发进程数设置高一点应该就好了，有空我再看看怎么优化

登录提示发送两条的原因应该是系统日志的监控进程（logread -f -p notice）有时候还是会有残留进程，因为现在是实时推送，不依赖主程序的 X 秒循环逻辑，之前改成了不再生成临时文件，看来还是得改一下

**Comment by sunyen** [comment]
感谢大佬回复，后来我重启了一下，发现3.5.6版本功能基本上都已经正常了(之前用着你今年更新的第一个版本不管怎么重启都不行)，登录提醒不会发送两条了，设备上线提醒也好像没什么问题了，另外就是设置成这样子之后，设备下线了过了好几分钟之后才会在插件里面的在线设备里面消失。
![Screenshot_2024-07-16-09-19-39-202_com microsoft emmx-edit](https://github.com/user-attachments/assets/98c65f07-3908-4da8-926e-3ac822080c96)
