### ISSUE TITLE
3.5.6版IP变化后推送消息中没有IP地址信息

### ISSUE THREAD

**Issue by beck023** [tty228/luci-app-wechatpush#300]
#### 您使用的场景？ | ImmortalWrt23.05.03

首先非常感谢大佬加入了IP排序的功能, 这是我之前提的一个request :)
升级到最新版后遇到一个问题, 当PPPOE 断线重拨IP地址改变了,能收到一条推送消息,但是只有title 和  设备信息,不包含当前的IPv4/IPv6地址, 在之前的3.4.2上是没有问题的, 我获取IP的方式是通过网络接口 pppoe-wan(ipv4) 和br-lan(ipv6), 定时推送中能正常推送IP信息

**Comment by tty228** [comment]
![image](https://github.com/user-attachments/assets/92f4d688-409f-445a-9458-a25257ec6da9)
无法复现，我这里正常

**Comment by beck023** [comment]
我这边始终只能推送title 和当前设备信息,缺了IP地址,所以我猜是不是被后面的内容覆盖了, 检查了下主程序,把current_device函数里的这一行: content="${explain}${header}"修改成content="${content}${explain}${header}"就可以了
