### ISSUE TITLE
保存表单出错，输入数字了还是报错

### ISSUE THREAD

**Issue by 363137946** [tty228/luci-app-wechatpush#301]
保存出现错误
保存表单时出错：

选项“当 CPU 温度或负载超过阈值持续超过（秒）”包含无效的输入值。 请输入：非空值

￼关闭

**Comment by harrison-guo-chn** [comment]
免打扰设置里面，那两个值要自己填

**Comment by 363137946** [comment]
晕，一直以为是推送内容那里面的，看了下才发现是免打扰那

**Comment by hange33** [comment]
建议新增一下没填数值的位置，找了半天没找到还好翻了issues

**Comment by tty228** [comment]
https://github.com/tty228/luci-app-wechatpush/commit/d6cfb8bda3963ea8a8f4dfbf0314d2f7bc8aea89
