### ISSUE TITLE
在线设备只能获取/24子网下的设备

### ISSUE THREAD

**Issue by LovelyToaster** [tty228/luci-app-wechatpush#304]
#### 您使用的版本？ | Your usage version?
V3.5.6
#### 您使用的场景？ | Your usage scenarios?
获取在线用户
#### 您遇到了什么问题？ | What are your problems?
在线用户获取不全
#### 您期望的结果是怎样的？ | What is your expected outcome?
我的网络是192.168.0.0/16的结构，当前版本只能获取192.168.0.0/24的设备，不能获取整个网络的在线设备。

建议增加一些常见的子网让用户选择，如/24，/16等等

获取/16子网下所有的在线设备应该修改脚本中1343-1344：
[ -n "$IP_INFO" ] && local SUBNET=$(echo $IP_INFO | cut -d'/' -f1 | cut -d'.' -f1-3)
[ -n "$SUBNET" ] && local IPLIST=$(cat /proc/net/arp | grep "0x2\|0x6" | awk '{print $1}' | grep -v "^169.254." | grep -v "^$" | sort -u | grep -oE "${SUBNET}\.[0-9]{1,3}") || local IPLIST=$(cat /proc/net/arp | grep "0x2\|0x6" | awk '{print $1}' | grep -v "^169.254." | grep -v "^$" | sort -u | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
改成
[ -n "$IP_INFO" ] && local SUBNET=$(echo $IP_INFO | cut -d'/' -f1 | cut -d'.' -f1-2)
[ -n "$SUBNET" ] && local IPLIST=$(cat /proc/net/arp | grep "0x2\|0x6" | awk '{print $1}' | grep -v "^169.254." | grep -v "^$" | sort -u | grep -oE "${SUBNET}\.[0-9]{1,3}\.[0-9]{1,3}") || local IPLIST=$(cat /proc/net/arp | grep "0x2\|0x6" | awk '{print $1}' | grep -v "^169.254." | grep -v "^$" | sort -u | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

**Comment by tty228** [comment]
bash 的语法获取指定掩码位有点麻烦，之前是无视掩码直接读取 arp 文件，不过这样会显示一些预料之外的 IP 段，所以加上了限制

**Comment by LovelyToaster** [comment]
> bash 的语法获取指定掩码位有点麻烦，之前是无视掩码直接读取 arp 文件，不过这样会显示一些预料之外的 IP 段，所以加上了限制

那我自己改改用吧👌
