### ISSUE TITLE
一直推送路由器重新启动

### ISSUE THREAD

**Issue by 363137946** [tty228/luci-app-wechatpush#305]
openwrt 6.6一直推送路由器重新启动是什么问题

**Comment by meteorain** [comment]
原因是推送内容中，“设备”符选错了，IPV4和IPV6一直取不到，两者都为空就会去推送“路由器已经重启”。建议多测试几个设备看哪个可以真正获取到IP。

**Comment by meteorain** [comment]
> openwrt 6.6一直推送路由器重新启动是什么问题

原因是推送内容中，“设备”符选错了，IPV4和IPV6一直取不到，两者都为空就会去推送“路由器已经重启”。建议多测试几个设备看哪个可以真正获取到IP。
