### ISSUE TITLE
请问下载地址中的两个文件分别是什么，谢谢

### ISSUE THREAD

**Issue by wqinf** [tty228/luci-app-wechatpush#310]
下载地址中有两个文件：
luci-app-wechatpush_3.5.6_all.ipk
luci-i18n-wechatpush-zh-cn_24.195.32270.071b978_all.ipk

请问这两个文件分别是什么，在说明中没有看到相关的描述，请问两个都要安装吗？谢谢

**Comment by k2y1982** [comment]
luci-app-wechatpush_3.5.6_all.ipk  主程序
luci-i18n-wechatpush-zh-cn_24.195.32270.071b978_all.ipk   中文包

**Comment by wqinf** [comment]
> luci-app-wechatpush_3.5.6_all.ipk 主程序 luci-i18n-wechatpush-zh-cn_24.195.32270.071b978_all.ipk 中文包

谢谢
